# Generated by Django 5.1 on 2024-08-24 13:32

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[validators.MaxSizeValidator(5242880)]),
        ),
    ]
