# Generated by Django 5.1 on 2024-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_of_birth',
            new_name='date_of_publication',
        ),
    ]
