# Generated by Django 5.1 on 2024-08-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
