# Generated by Django 5.1 on 2024-09-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='PhotoLike',
        ),
    ]
