# Generated by Django 5.1 on 2024-09-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_like_photolike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photolike',
            old_name='to_photo',
            new_name='pet_photo',
        ),
    ]
