# Generated by Django 5.1 on 2024-09-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_comment_to_photo_alter_photolike_pet_photo'),
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
