# Generated by Django 5.1 on 2024-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(upload_to='pet_photos/'),
        ),
    ]
