# Generated by Django 5.1 on 2024-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.URLField(blank=True),
        ),
    ]
